[#fix] Build error
1. We should enable the change with `ssr` only when the `mode` is "development" in `vite.config.ts`
1. The following error causes 500. Stop reusing DB connections to mitigate the issue.

> Error: Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance.